# Generated by Django 4.0.5 on 2022-08-31 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_videos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
