# Generated by Django 4.0.5 on 2022-08-31 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_alter_video_options_rename_video_video_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
    ]
