# Generated by Django 4.0.5 on 2022-08-31 19:50

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='url',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
