# Generated by Django 4.0.5 on 2022-09-01 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_room_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
