# Generated by Django 4.0.5 on 2022-09-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
